spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/hello_java
#    username: demo_java
#    password: 123456

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    
  sql:
    init:
      platform: mysql
      mode: always
    
   
     

#spring.sql.init.platform=mysql
#spring.sql.init.mode=always
#spring.datasource.url=jdbc:mysql://mysqldb:3306/mydb
##spring.datasource.username=root
##spring.datasource.password=123456
##spring.jpa.hibernate.ddl-auto=update